version: "3.7"
services:
  webserver:
    build:
      context: '../'
      dockerfile: './docker/Dockerfile'
      args:
       PHP_VERSION: 8.2
    links:
      - mailcatcher
    restart: always
    volumes:
      - /var/www/request-response:/var/www/html/
      - './php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
      - './90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini'
    container_name: "php"
    ports:
        - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "a654321"
      MYSQL_DATABASE: "laravel"
      MYSQL_PASSWORD: "a654321"
    container_name: "db"
  mailcatcher:
    image: tophfr/mailcatcher
    container_name: mailcatcher
    ports:
      - '2080:80'
      - '2025:25'
    restart: always

